=== webOS-ports/webos-keyboard/data/styles/ubuntu/languages/VirtualKeyboardLayout.dtd
<!ELEMENT keyboard (layout | import)*>
<!ELEMENT import (symview | phonenumber | number)*>
<!ELEMENT symview EMPTY>
<!ELEMENT phonenumber EMPTY>
<!ELEMENT number EMPTY>
<!ELEMENT layout (section+)>
<!ELEMENT section (row+)>
<!ELEMENT row (key | spacer)*>
<!-- That is bit too broad - allows to specify two <extended> in <key>. Our
layout parser will issue an error if this happens. -->
<!ELEMENT key (extended?,binding,extended?)>
<!ELEMENT spacer EMPTY>
<!ELEMENT binding (modifiers)*>
<!ELEMENT extended (row+)>
<!ELEMENT modifiers (binding)>

<!ATTLIST keyboard
  version CDATA "1.0"
  title CDATA #IMPLIED
  language CDATA #IMPLIED
  catalog CDATA #IMPLIED
  autocapitalization (true | false) "true">

<!--
file: File to import, deprecated in favour of <symview>, <phonenumber> and <number>.
-->
<!ATTLIST import
  file CDATA #IMPLIED>

<!ATTLIST symview
  src CDATA #REQUIRED>

<!ATTLIST phonenumber
  src CDATA #REQUIRED>

<!ATTLIST number
  src CDATA #REQUIRED>

<!ATTLIST layout
  type (general | url | email | number | phonenumber | common) "general"
  orientation (landscape | portrait) "landscape"
  uniform-font-size (true | false) "false"
>

<!ATTLIST section
  id CDATA #REQUIRED
  movable (true | false) "true"
  type (sloppy | non-sloppy) "sloppy"
  style CDATA #IMPLIED
>

<!ATTLIST row
  height (small | medium | large | x-large | xx-large) "medium"
>

<!--
style:
width:
rtl: Something with right-to-left, but the same exists for <binding>.
id: An ID for key overrides, not used.
-->
<!ATTLIST key
  style (normal | special | deadkey) "normal"
  width (small | medium | large | x-large | xx-large | stretched) "medium"
  rtl (true | false) "false"
  id CDATA #IMPLIED
>

<!--
label: Key's label.
secondary_label: ? Not used.
accents: Which accents are activating accented_labels.
accented_labels: What accented labels should be shown for given accents.
cycleset: ? Not used.
dead: Whether key is a dead key.
quickpick: ? Not used.
rtl: ? Not used.
enlarge: ? Not used.
sequence: Sequence of keys this key imitates, valid only for command action.
icon: Icon to be used.
-->
<!ATTLIST binding
  action (insert | shift | backspace | space | cycle | layout_menu | sym
          | return | commit | decimal_separator | plus_minus_toggle | switch
          | on_off_toggle | compose | left | up | right | down | close
          | left-layout | right-layout) "insert"
  label CDATA #IMPLIED
  secondary_label CDATA #IMPLIED
  accents CDATA #IMPLIED
  accented_labels CDATA #IMPLIED
  cycleset CDATA #IMPLIED
  dead (true | false) "false"
  quickpick (true | false) "false"
  rtl (true | false) "false"
  enlarge (true | false) "false"
  sequence CDATA #IMPLIED
  icon CDATA #IMPLIED
>

<!ATTLIST modifiers
  keys (alt|shift|altshift) #REQUIRED
>

=== webOS-ports/webos-keyboard/data/styles/ubuntu/languages/toolbar.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM "VirtualKeyboardLayout.dtd">

<keyboard title="Toolbar" version="1.0">
  <layout type="general">
    <section id="main">
      <row>
        <key>
          <binding action="left" label="←" />
        </key>
        <key>
          <binding action="right" label="→" />
        </key>
      </row>
    </section>
  </layout>
</keyboard>

=== webOS-ports/webos-keyboard/data/styles/ubuntu/languages/uk.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM "VirtualKeyboardLayout.dtd">

<keyboard catalog="" language="uk" title="Українська" version="1.0">
  <layout type="general">
    <section id="main">
      <row>
        <key>
          <binding label="й">
            <modifiers keys="shift">
              <binding label="Й" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="ц">
            <modifiers keys="shift">
              <binding label="Ц" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="у">
            <modifiers keys="shift">
              <binding label="У" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="к">
            <modifiers keys="shift">
              <binding label="К" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="е">
            <modifiers keys="shift">
              <binding label="Е" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="н">
            <modifiers keys="shift">
              <binding label="Н" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="г">
            <modifiers keys="shift">
              <binding label="Г" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="ш">
            <modifiers keys="shift">
              <binding label="Ш" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="щ">
            <modifiers keys="shift">
              <binding label="Щ" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="з">
            <modifiers keys="shift">
              <binding label="З" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="х">
            <modifiers keys="shift">
              <binding label="Х" />
            </modifiers>
          </binding>
        </key>
      </row>
      <row>
        <key>
          <binding label="ф">
            <modifiers keys="shift">
              <binding label="Ф" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="і">
            <modifiers keys="shift">
              <binding label="І" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="в">
            <modifiers keys="shift">
              <binding label="В" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="а">
            <modifiers keys="shift">
              <binding label="А" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="п">
            <modifiers keys="shift">
              <binding label="П" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="р">
            <modifiers keys="shift">
              <binding label="Р" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="о">
            <modifiers keys="shift">
              <binding label="О" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="л">
            <modifiers keys="shift">
              <binding label="Л" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="д">
            <modifiers keys="shift">
              <binding label="Д" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="ж">
            <modifiers keys="shift">
              <binding label="Ж" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="є">
            <modifiers keys="shift">
              <binding label="Є" />
            </modifiers>
          </binding>
        </key>
      </row>
      <row>
        <key style="special">
          <binding action="shift" />
        </key>
        <key>
          <binding label="ґ">
            <modifiers keys="shift">
              <binding label="Ґ" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="я">
            <modifiers keys="shift">
              <binding label="Я" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="ч">
            <modifiers keys="shift">
              <binding label="Ч" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="с">
            <modifiers keys="shift">
              <binding label="С" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="м">
            <modifiers keys="shift">
              <binding label="М" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="и">
            <modifiers keys="shift">
              <binding label="И" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="т">
            <modifiers keys="shift">
              <binding label="Т" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="ь">
            <modifiers keys="shift">
              <binding label="Ь" />
            </modifiers>
          </binding>
        </key>
        <key>
          <binding label="б">
            <modifiers keys="shift">
              <binding label="Б" />
            </modifiers>
          </binding>
        </key>
        <key style="special">
          <binding action="backspace" />
        </key>
      </row>
      <row>
        <key style="special" width="large">
          <binding action="sym" label="?123" />
        </key>
        <key>
          <binding label="ї">
            <modifiers keys="shift">
              <binding label="Ї" />
            </modifiers>
          </binding>
        </key>
        <key id="emailUrlKey">
          <binding label="," />
        </key>
        <key width="xx-large">
          <binding action="space" label="" />
        </key>
        <key>
          <binding label="." />
        </key>
        <key>
          <binding label="ю">
            <modifiers keys="shift">
              <binding label="Ю" />
            </modifiers>
          </binding>
        </key>
        <key id="actionKey" style="special" width="x-large">
          <binding action="return" />
        </key>
      </row>
    </section>
  </layout>
  <import file="symbols_ru_uk.xml" />
</keyboard>

=== webOS-ports/webos-keyboard/data/styles/ubuntu/languages/symbols_en.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM "VirtualKeyboardLayout.dtd">

<keyboard catalog="symbols" version="1.0">
  <layout type="general">
    <section id="symbols0" type="non-sloppy">
      <row>
        <key>
          <binding label="1" />
        </key>
        <key>
          <binding label="2" />
        </key>
        <key>
          <binding label="3" />
        </key>
        <key>
          <binding label="4" />
        </key>
        <key>
          <binding label="5" />
        </key>
        <key>
          <binding label="6" />
        </key>
        <key>
          <binding label="7" />
        </key>
        <key>
          <binding label="8" />
        </key>
        <key>
          <binding label="9" />
        </key>
        <key>
          <binding label="0" />
        </key>
      </row>
      <row>
        <spacer />
        <key>
          <binding label="*" />
        </key>
        <key>
          <binding label="#" />
        </key>
        <key>
          <binding label="+" />
        </key>
        <key>
          <binding label="-" />
        </key>
        <key>
          <binding label="=" />
        </key>
        <key>
          <binding label="(" />
        </key>
        <key>
          <binding label=")" />
        </key>
        <key>
          <binding label="!" />
        </key>
        <key>
          <binding label="?" />
        </key>
        <spacer />
      </row>
      <row>
        <key style="special" width="large">
          <binding action="switch" label="1/2" />
        </key>
        <spacer />
        <key>
          <binding label="@" quickpick="true" />
        </key>
        <key>
          <binding label="~" />
        </key>
        <key>
          <binding label="/" />
        </key>
        <key>
          <binding label="\" />
        </key>
        <key>
          <binding label="'" quickpick="true" />
        </key>
        <key>
          <binding label=";" />
        </key>
        <key>
          <binding label=":" />
        </key>
        <spacer />
        <key style="special" width="large">
          <binding action="backspace" />
        </key>
      </row>
      <row>
        <key style="special" width="x-large">
          <binding action="sym" label="ABC" />
        </key>
        <spacer />
        <key>
          <binding label="," />
        </key>
        <key width="xx-large">
          <binding action="space" />
        </key>
        <key>
          <binding label="." />
        </key>
        <spacer />
        <key id="actionKey" style="special" width="x-large">
          <binding action="return" />
        </key>
      </row>
    </section>
    <section id="symbols1" type="non-sloppy">
      <row>
        <key>
          <binding label="€" />
        </key>
        <key>
          <binding label="£" />
        </key>
        <key>
          <binding label="$" />
        </key>
        <key>
          <binding label="¥" />
        </key>
        <key>
          <binding label="₹" />
        </key>
        <key>
          <binding label="%" />
        </key>
        <key>
          <binding label="&lt;" />
        </key>
        <key>
          <binding label="&gt;" />
        </key>
        <key>
          <binding label="[" />
        </key>
        <key>
          <binding label="]" />
        </key>
      </row>
      <row>
        <spacer />
        <key>
          <binding label="`" />
        </key>
        <key>
          <binding label="^" />
        </key>
        <key>
          <binding label="|" />
        </key>
        <key>
          <binding label="_" />
        </key>
        <key>
          <binding label="§" />
        </key>
        <key>
          <binding label="{" />
        </key>
        <key>
          <binding label="}" />
        </key>
        <key>
          <binding label="¡" />
        </key>
        <key>
          <binding label="¿" />
        </key>
        <spacer />
      </row>
      <row>
        <key style="special" width="large">
          <binding action="switch" label="2/2" />
        </key>
        <spacer />
        <key>
          <binding label="«" />
        </key>
        <key>
          <binding label="»" />
        </key>
        <key>
          <binding label="&quot;" />
        </key>
        <key>
          <binding label="“" />
        </key>
        <key>
          <binding label="”" />
        </key>
        <key>
          <binding label="„" />
        </key>
        <key>
          <binding label="&amp;" />
        </key>
        <spacer />
        <key style="special" width="large">
          <binding action="backspace" />
        </key>
      </row>
      <row>
        <key style="special" width="x-large">
          <binding action="sym" label="ABC" />
        </key>
        <spacer />
        <key>
          <binding label="," />
        </key>
        <key width="xx-large">
          <binding action="space" />
        </key>
        <key>
          <binding label="." />
        </key>
        <spacer />
        <key id="actionKey" style="special" width="x-large">
          <binding action="return" />
        </key>
      </row>
    </section>
  </layout>
</keyboard>

=== webOS-ports/webos-keyboard/data/styles/ubuntu/languages/phonenumber.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM "VirtualKeyboardLayout.dtd">

<keyboard catalog="phonenumber" title="Phone Number" version="1.0">
  <layout orientation="landscape" type="phonenumber">
    <section id="main" movable="false">
      <row height="x-large">
        <key>
          <binding label="1" />
        </key>
        <key>
          <binding label="2" secondary_label="abc" />
        </key>
        <key>
          <binding label="3" secondary_label="def" />
        </key>
        <key>
          <binding label="4" secondary_label="ghi" />
        </key>
        <key>
          <binding label="5" secondary_label="jkl" />
        </key>
        <key>
          <binding label="6" secondary_label="mno" />
        </key>
        <key>
          <binding label="7" secondary_label="pqrs" />
        </key>
        <key>
          <binding label="8" secondary_label="tuv" />
        </key>
        <key>
          <binding label="9" secondary_label="wxyz" />
        </key>
        <key>
          <binding label="0" />
        </key>
      </row>
      <row>
        <spacer />
        <key width="large">
          <binding action="cycle" cycleset="*+p" label="*+" />
        </key>
        <key width="large">
          <binding label="#" />
        </key>
        <key style="special" width="large">
          <binding action="backspace" label="" />
        </key>
        <key id="actionKey" style="special" width="large">
          <binding action="return" />
        </key>
      </row>
    </section>
  </layout>
  <layout orientation="portrait" type="phonenumber">
    <section id="main" movable="false">
      <row>
        <key>
          <binding label="1" />
        </key>
        <key>
          <binding label="2" secondary_label="abc" />
        </key>
        <key>
          <binding label="3" secondary_label="def" />
        </key>
      </row>
      <row>
        <key>
          <binding label="4" secondary_label="ghi" />
        </key>
        <key>
          <binding label="5" secondary_label="jkl" />
        </key>
        <key>
          <binding label="6" secondary_label="mno" />
        </key>
      </row>
      <row>
        <key>
          <binding label="7" secondary_label="pqrs" />
        </key>
        <key>
          <binding label="8" secondary_label="tuv" />
        </key>
        <key>
          <binding label="9" secondary_label="wxyz" />
        </key>
      </row>
      <row>
        <key>
          <binding action="cycle" cycleset="*+p" label="*+" />
        </key>
        <key>
          <binding label="0" />
        </key>
        <key>
          <binding label="#" />
        </key>
      </row>
      <row>
        <key style="special" width="large">
          <binding action="backspace" label="" />
        </key>
        <spacer />
        <key id="actionKey" style="special">
          <binding action="return" />
        </key>
      </row>
    </section>
  </layout>
</keyboard>

=== webOS-ports/webos-keyboard/data/styles/ubuntu/languages/number.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM "VirtualKeyboardLayout.dtd">

<keyboard catalog="number" title="Number" version="1.0">
  <layout orientation="landscape" type="number">
    <section id="main" movable="false">
      <row>
        <key width="x-large">
          <binding label="1" />
        </key>
        <key width="x-large">
          <binding label="2" />
        </key>
        <key width="x-large">
          <binding label="3" />
        </key>
      </row>
      <row>
        <key width="x-large">
          <binding label="4" />
        </key>
        <key width="x-large">
          <binding label="5" />
        </key>
        <key width="x-large">
          <binding label="6" />
        </key>
      </row>
      <row>
        <key width="x-large">
          <binding label="7" />
        </key>
        <key width="x-large">
          <binding label="8" />
        </key>
        <key width="x-large">
          <binding label="9" />
        </key>
      </row>
      <row>
        <key width="x-large">
          <binding action="plus_minus_toggle" label="+/-" />
        </key>
        <key width="x-large">
          <binding label="0" />
        </key>
        <key style="special" width="x-large">
          <binding action="backspace" label="" />
        </key>
      </row>
    </section>
  </layout>
  <layout orientation="portrait" type="number">
    <section id="main" movable="false">
      <row>
        <key>
          <binding label="1" />
        </key>
        <key>
          <binding label="2" />
        </key>
        <key>
          <binding label="3" />
        </key>
      </row>
      <row>
        <key>
          <binding label="4" />
        </key>
        <key>
          <binding label="5" />
        </key>
        <key>
          <binding label="6" />
        </key>
      </row>
      <row>
        <key>
          <binding label="7" />
        </key>
        <key>
          <binding label="8" />
        </key>
        <key>
          <binding label="9" />
        </key>
      </row>
      <row>
        <key>
          <binding action="plus_minus_toggle" label="+/-" />
        </key>
        <key>
          <binding label="0" />
        </key>
        <key>
          <binding action="decimal_separator" />
        </key>
      </row>
      <row>
        <key style="special" width="large">
          <binding action="backspace" label="" />
        </key>
        <spacer />
        <key id="actionKey" style="special">
          <binding action="return" />
        </key>
      </row>
    </section>
  </layout>
</keyboard>

=== webOS-ports/webos-keyboard/data/styles/ubuntu/languages/symbols-39.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM "VirtualKeyboardLayout.dtd">

<keyboard catalog="symbols" version="1.0">
  <layout type="general">
    <section id="symbols0" type="non-sloppy">
      <row>
        <key>
          <binding label="1" />
        </key>
        <key>
          <binding label="2" />
        </key>
        <key>
          <binding label="3" />
        </key>
        <key>
          <binding label="4" />
        </key>
        <key>
          <binding label="5" />
        </key>
        <key>
          <binding label="6" />
        </key>
        <key>
          <binding label="7" />
        </key>
        <key>
          <binding label="8" />
        </key>
        <key>
          <binding label="9" />
        </key>
        <key>
          <binding label="0" />
        </key>
        <key>
          <binding label="%" />
        </key>
      </row>
      <row>
        <key>
          <binding label="*" />
        </key>
        <key>
          <binding label="#" />
        </key>
        <key>
          <binding label="+" />
        </key>
        <key>
          <binding label="-" />
        </key>
        <key>
          <binding label="=" />
        </key>
        <key>
          <binding label="(" />
        </key>
        <key>
          <binding label=")" />
        </key>
        <key>
          <binding label=";" />
        </key>
        <key>
          <binding label=":" />
        </key>
        <key>
          <binding label="!" />
        </key>
        <key>
          <binding label="?" />
        </key>
      </row>
      <row>
        <key style="special" width="x-large">
          <binding action="switch" label="1/2" />
        </key>
        <key>
          <binding label="@" quickpick="true" />
        </key>
        <key>
          <binding label="~" />
        </key>
        <key>
          <binding label="/" />
        </key>
        <key>
          <binding label="\" />
        </key>
        <key>
          <binding label="'" quickpick="true" />
        </key>
        <key>
          <binding label="&quot;" />
        </key>
        <key>
          <binding label="°" />
        </key>
        <key>
          <binding label="&amp;" />
        </key>
        <key style="special" width="x-large">
          <binding action="backspace" />
        </key>
      </row>
      <row>
        <key style="special" width="x-large">
          <binding action="sym" label="ABC" />
        </key>
        <key>
          <binding label="_" />
        </key>
        <key>
          <binding label="," />
        </key>
        <key width="stretched">
          <binding action="space" />
        </key>
        <key>
          <binding label="." />
        </key>
        <key>
          <binding label="—" />
        </key>
        <key id="actionKey" style="special" width="xx-large">
          <binding action="return" />
        </key>
      </row>
    </section>
    <section id="symbols1" type="non-sloppy">
      <row>
        <key>
          <binding label="1" />
        </key>
        <key>
          <binding label="2" />
        </key>
        <key>
          <binding label="3" />
        </key>
        <key>
          <binding label="4" />
        </key>
        <key>
          <binding label="5" />
        </key>
        <key>
          <binding label="6" />
        </key>
        <key>
          <binding label="7" />
        </key>
        <key>
          <binding label="8" />
        </key>
        <key>
          <binding label="9" />
        </key>
        <key>
          <binding label="0" />
        </key>
        <key>
          <binding label="‰" />
        </key>
      </row>
      <row>
        <key>
          <binding label="€" />
        </key>
        <key>
          <binding label="£" />
        </key>
        <key>
          <binding label="$" />
        </key>
        <key>
          <binding label="¥" />
        </key>
        <key>
          <binding label="§" />
        </key>
        <key>
          <binding label="[" />
        </key>
        <key>
          <binding label="]" />
        </key>
        <key>
          <binding label="{" />
        </key>
        <key>
          <binding label="}" />
        </key>
        <key>
          <binding label="¡" />
        </key>
        <key>
          <binding label="¿" />
        </key>
      </row>
      <row>
        <key style="special" width="x-large">
          <binding action="switch" label="2/2" />
        </key>
        <key>
          <binding label="`" />
        </key>
        <key>
          <binding label="^" />
        </key>
        <key>
          <binding label="|" />
        </key>
        <key>
          <binding label="“" />
        </key>
        <key>
          <binding label="”" />
        </key>
        <key>
          <binding label="„" />
        </key>
        <key>
          <binding label="«" />
        </key>
        <key>
          <binding label="»" />
        </key>
        <key style="special" width="x-large">
          <binding action="backspace" />
        </key>
      </row>
      <row>
        <key style="special" width="x-large">
          <binding action="sym" label="ABC" />
        </key>
        <key>
          <binding label="&lt;" />
        </key>
        <key>
          <binding label="&gt;" />
        </key>
        <key width="stretched">
          <binding action="space" />
        </key>
        <key>
          <binding label="©" />
        </key>
        <key>
          <binding label="®" />
        </key>
        <key id="actionKey" style="special" width="xx-large">
          <binding action="return" />
        </key>
      </row>
    </section>
  </layout>
</keyboard>
